"""
doc_export.py
=============
Build a tailored resume DOCX from the final structured resume dict (see
resume_builder.merge_tailored_resume), and convert that DOCX to PDF using
LibreOffice's headless mode (cross-platform, no MS Word / docx2pdf
dependency required).

If LibreOffice is not installed, PDF export is skipped gracefully and the
caller is told so (DOCX is always available).
"""
from __future__ import annotations
import io
import os
import shutil
import subprocess
import tempfile


def build_tailored_docx(final_resume: dict, candidate_name: str = "") -> bytes:
    """Render the final structured resume dict into a clean DOCX file (bytes).

    NOTE: `final_resume["notes"]` (gap-analysis commentary) is intentionally
    NEVER written into the document -- it is for on-screen review only.
    """
    import docx
    from docx.shared import Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = docx.Document()

    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(10.5)

    contact = final_resume.get("contact", {}) or {}
    name = candidate_name.strip() or contact.get("name", "").strip()
    if name:
        h = doc.add_heading(name, level=0)
        h.alignment = WD_ALIGN_PARAGRAPH.CENTER

    contact_line = " | ".join(
        v for v in (contact.get("email"), contact.get("phone"),
                    contact.get("linkedin"), contact.get("location")) if v and v.strip()
    )
    if contact_line:
        p = doc.add_paragraph(contact_line)
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    summary = (final_resume.get("summary") or "").strip()
    if summary:
        doc.add_heading("Professional Summary", level=1)
        doc.add_paragraph(summary)

    skills = final_resume.get("skills") or []
    if skills:
        doc.add_heading("Skills", level=1)
        doc.add_paragraph(" • ".join(skills))

    experience = final_resume.get("experience") or []
    if experience:
        doc.add_heading("Experience", level=1)
        for entry in experience:
            header_parts = [p for p in (entry.get("title"), entry.get("company")) if p]
            header = " — ".join(header_parts)
            dates = entry.get("dates", "")
            p = doc.add_paragraph()
            if header:
                run = p.add_run(header)
                run.bold = True
                run.font.size = Pt(11)
            if dates:
                tab_run = p.add_run(f"\t{dates}")
                tab_run.italic = True
                tab_run.font.size = Pt(10)
            for bullet in entry.get("bullets", []):
                doc.add_paragraph(bullet, style="List Bullet")

    projects = final_resume.get("projects") or []
    if projects:
        doc.add_heading("Projects", level=1)
        for proj in projects:
            if proj.get("name"):
                p = doc.add_paragraph()
                run = p.add_run(proj["name"])
                run.bold = True
                run.font.size = Pt(11)
            for bullet in proj.get("bullets", []):
                doc.add_paragraph(bullet, style="List Bullet")

    education = final_resume.get("education") or []
    if education:
        doc.add_heading("Education", level=1)
        for edu in education:
            line_parts = [p for p in (edu.get("degree"), edu.get("institution")) if p]
            line = " — ".join(line_parts)
            dates = edu.get("dates", "")
            p = doc.add_paragraph()
            if line:
                run = p.add_run(line)
                run.bold = True
            if dates:
                tab_run = p.add_run(f"\t{dates}")
                tab_run.italic = True

    certifications = final_resume.get("certifications") or []
    if certifications:
        doc.add_heading("Certifications", level=1)
        doc.add_paragraph(" • ".join(certifications))

    # Deliberately NOT writing final_resume["notes"] into the document.
    # Those gap-analysis notes are shown only in the app UI for review.

    _scrub_docx_metadata(doc, name)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _scrub_docx_metadata(doc, candidate_name: str = "") -> None:
    """Clear core document properties that could reveal this file was
    generated by a script (author username, company, generating application,
    revision history) rather than typed directly in Word.

    This is a privacy/hygiene step, independent of resume content honesty:
    the resume's claims are still fully truthful, we're just not leaking
    "python-docx" / a random local username into the file's metadata.
    """
    core = doc.core_properties
    core.author = candidate_name or ""
    core.last_modified_by = candidate_name or ""
    core.comments = ""
    core.category = ""
    core.content_status = ""
    core.identifier = ""
    core.keywords = ""
    core.subject = ""
    try:
        core.revision = 1
    except Exception:
        pass


def docx_bytes_to_pdf(docx_bytes: bytes) -> bytes | None:
    """Convert DOCX bytes to PDF bytes via headless LibreOffice.

    Returns None if `soffice` (LibreOffice) is not found on PATH.
    """
    soffice = shutil.which("soffice") or shutil.which("libreoffice")
    if not soffice:
        return None

    with tempfile.TemporaryDirectory() as tmpdir:
        docx_path = os.path.join(tmpdir, "resume.docx")
        with open(docx_path, "wb") as f:
            f.write(docx_bytes)
        subprocess.run(
            [soffice, "--headless", "--convert-to", "pdf", "--outdir", tmpdir, docx_path],
            check=True, capture_output=True, timeout=90,
        )
        pdf_path = os.path.join(tmpdir, "resume.pdf")
        if not os.path.exists(pdf_path):
            return None
        with open(pdf_path, "rb") as f:
            return f.read()


def libreoffice_available() -> bool:
    return bool(shutil.which("soffice") or shutil.which("libreoffice"))
